exclude: ^(.idea|.vscode)/
default_stages: [push]
fail_fast: false
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    # https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.12"
    hooks:
      - id: ruff
        name: python ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: rust format
        description: Run Cargo fmt on files included in the commit
        entry: bash -c 'cargo fmt'
        pass_filenames: true
        types: [file, rust]
        language: system

      - id: cargo-clippy
        name: rust lint
        description: Run Cargo clippy on files included in the commit
        entry: bash -c 'cargo clippy'
        pass_filenames: false
        types: [file, rust]
        language: system
